import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

// Intentionally-unused bindings are prefixed with `_` across the suite
// (e.g. object-rest omission `const { x: _omit, ...rest } = obj`).
const unusedVars = [
  "error",
  { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
];

export default tseslint.config(
  {
    ignores: [
      "dist",
      ".vite",
      "node_modules",
      "test-results",
      "playwright-report",
      // Generated by scripts/build-worklet.mjs — never edit or lint.
      "src/engine/voiceProcessor.js",
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["src/**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": [
        "warn",
        { allowConstantExport: true },
      ],
      "@typescript-eslint/no-unused-vars": unusedVars,
      // The App relies on a documented ref-mirror pattern — `xxxRef.current =
      // xxx` written during render so scheduler callbacks (which run outside
      // React) read fresh state (see docs/development.md gotchas). The
      // React-Compiler heuristics in these two rules flag that intentional
      // pattern and the guarded/mount-only effects around it; the behaviour is
      // load-bearing, so they are relaxed rather than the logic changed.
      "react-hooks/refs": "off",
      "react-hooks/set-state-in-effect": "off",
    },
  },
  {
    // Tests run in Node under Vitest/Playwright and import their own
    // globals, so no ambient test globals — just add Node builtins.
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["tests/**/*.ts"],
    languageOptions: {
      ecmaVersion: 2022,
      globals: { ...globals.browser, ...globals.node },
    },
    rules: {
      "@typescript-eslint/no-unused-vars": unusedVars,
      // Tests cast to `any` to inspect union-member internals of engine
      // events; acceptable in test-only code.
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
);
