// Concatenate worklet sources into a single file (ES module imports aren't
// portable inside AudioWorklet). Mirrors ../mdrone/scripts/build-worklet.mjs.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const parts = ["src/engine/voices/shared.js", "src/engine/voices/karplus.js"];
const banner = "// GENERATED by scripts/build-worklet.mjs — do not edit.\n";
const body = parts.map((p) => readFileSync(join(root, p), "utf8")).join("\n");
writeFileSync(join(root, "src/engine/voiceProcessor.js"), banner + body);
console.log("built src/engine/voiceProcessor.js");
